"""initial

Revision ID: 2fe9924272a9
Revises: be94de998e1c
Create Date: 2023-10-05 14:27:55.050844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fe9924272a9'
down_revision: Union[str, None] = 'be94de998e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_comment')
    op.drop_table('post_likes')
    op.alter_column('users', 'registered_on',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'registered_on',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_table('post_likes',
    sa.Column('like_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='post_likes_author_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['like_id'], ['likes.id'], name='post_likes_like_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_likes_post_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('like_id', 'post_id', 'author_id', name='post_likes_pkey')
    )
    op.create_table('post_comment',
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='post_comment_author_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='post_comment_comment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_comment_post_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', name='post_comment_pkey')
    )
    # ### end Alembic commands ###
