"""auto-generated migration

Revision ID: be94de998e1c
Revises: 9034372b757d
Create Date: 2023-10-05 14:05:32.827340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be94de998e1c'
down_revision: Union[str, None] = '9034372b757d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_comment')
    op.drop_table('post_likes')
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.add_column('likes', sa.Column('post_id', sa.Integer(), nullable=False))
    op.add_column('likes', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'likes', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_column('likes', 'author_id')
    op.drop_column('likes', 'post_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'author_id')
    op.drop_column('comments', 'post_id')
    op.create_table('post_likes',
    sa.Column('like_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='post_likes_author_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['like_id'], ['likes.id'], name='post_likes_like_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_likes_post_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('like_id', 'post_id', 'author_id', name='post_likes_pkey')
    )
    op.create_table('post_comment',
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='post_comment_author_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='post_comment_comment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_comment_post_id_fkey', ondelete='CASCADE')
    )
    # ### end Alembic commands ###
